# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('sur_name', models.CharField(blank=True, max_length=40)),
                ('user_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('job', models.CharField(blank=True, max_length=40)),
                ('user_image', models.ImageField(upload_to='')),
                ('info_source', models.CharField(choices=[('a', 'Announcments'), ('b', 'Social networks'), ('c', 'Friends'), ('d', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
