# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='info_source',
            field=models.CharField(blank=True, choices=[('a', 'Announcments'), ('b', 'Social networks'), ('c', 'Friends'), ('d', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
