# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20160923_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
