# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20160924_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='scramble_uploaded_filename', verbose_name='uploaded images'),
        ),
    ]
