# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20160924_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='info_source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
